### ISSUE TITLE
readme.txt file is not good enough

### ISSUE THREAD

**Issue by digonto0912** [madeindjs/invoice-generator#1]
Your README file never includes images or descriptions of how it looks after use. If I don’t know how it looks afterward, why would I waste my time on this?

I recommend that you check out the best README file ->>>

1. https://www.npmjs.com/package/nice-invoice.
2. https://www.npmjs.com/package/easyinvoice

note:
Q: Why do I like your package?  
Ans: Because you offer a freedom that others never provide, which is the ability to add dynamic columns in items [maybe].

**Comment by madeindjs** [comment]
Hello, there is a link to a [PDF example](https://github.com/madeindjs/invoice-generator-pdf/blob/e617167d200331384da4e469efb6e6972c73240d/example.json.pdf) mentioned in the README.md:

https://github.com/madeindjs/invoice-generator-pdf/blob/e617167d200331384da4e469efb6e6972c73240d/README.md?plain=1#L33
